env:
  env_name: Lift
  robots: Panda
  reward_shaping: True
  has_offscreen_renderer: False
  use_camera_obs: False
  camera_heights: 84
  camera_widths: 84
  use_touch_obs: True
  controller_configs:
    default_controller: OSC_POSE
policy:
  policy_name: SAC
  total_timesteps: 6000000
  buffer_size: 1000000
  features_extractor:
    object_feature_dim: 128
    proprio_feature_dim: 128
    touch_feature_dim: 64
  suffix: touch




